### ISSUE TITLE
Intermittent issues with no sound on iOS

### ISSUE THREAD

**Issue by diatche** [adrianlyjak/obsidian-aloud-tts#13]
Hi, thanks for a great plugin! It works great on Mac, but on iOS, there's neither sound, nor controls when I press "Aloud: text to speech".

Since I sync with Working Copy, I can confirm that the sound files are being generated in the `.tts` directory and can be played from directly from there (the audio content matches the text in the note).

iOS Version: 17.2.1
Model: iPhone 11 Pro Max

**Comment by adrianlyjak** [comment]
Thanks for the report. It's strange, I've successfully tested on both iPhone (12 pro, also iOS version 17.2.1) and iPad.

One thought: the user interaction for this plugin is a little awkward on phones: Have you placed your cursor in a document ahead of selecting "Aloud: Text to speech"? If not, there should be  a notification saying "No text selected to speak." 

Otherwise, something around your configuration is different from mine, and is causing the plugin to crash. 😕 I may need to get creative to help you debug since I can't easily recreate it.

**Comment by diatche** [comment]
This may have been a now resolved bug in Obsidian or just a system issue, since today it worked perfectly. Thanks for offering a debug session 👍🏻

**Comment by adrianlyjak** [comment]
Hopefully fixed in #51, feel free to open a new issue if you encounter similar issues.
